# Generated by Django 5.1.1 on 2024-10-03 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="language",
            old_name="lang",
            new_name="language",
        ),
    ]
